import Head from 'next/head'
import styles from './style.module.scss'

export const Layout = ({children}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Fazueli Wallet</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                { children }
            </main>
        </div>
    )
}
