CREATE TABLE IF NOT EXISTS WALLET (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(256) NOT NULL UNIQUE,
    PASSWORD_SHA256_SUM VARCHAR(256) NOT NULL,
    BALANCE REAL(10,2) NOT NULL
);
